### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by luzik** [seifane/whisper-rhasspy-http#3]
When using "speech to text" like _Mozilla deep speech_ with "wake up" button it is ok, when switching to http remote with whisper-rhasspy url and using upload wav - it is ok, but after pressing "wake up" button I've got TimeoutError and this in logs:

```
[ERROR:2023-04-25 18:35:33,038] rhasspyserver_hermes: 
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 943, in api_listen_for_command
    async for response in core.publish_wait(handle_intent(), [], message_types):
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 995, in publish_wait
    result_awaitable, timeout=timeout_seconds
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[DEBUG:2023-04-25 18:35:03,016] rhasspyserver_hermes: <- HotwordDetected(model_id='default', model_version='', model_type='personal', current_sensitivity=1.0, site_id='default', session_id=None, send_audio_captured=None, lang=None, custom_entities=None)
[DEBUG:2023-04-25 18:35:03,015] rhasspyserver_hermes: Waiting for intent (session_id=None)
[DEBUG:2023-04-25 18:35:03,015] rhasspyserver_hermes: Publishing 199 bytes(s) to hermes/hotword/default/detected
[DEBUG:2023-04-25 18:35:03,015] rhasspyserver_hermes: -> HotwordDetected(model_id='default', model_version='', model_type='personal', current_sensitivity=1.0, site_id='default', session_id=None, send_audio_captured=None, lang=None, custom_entities=None)
```

I am not sure what is going on

**Comment by seifane** [comment]
@luzik It might be that you chose a model that is too big for your computer and it takes took long to process the audio. I am not sure on how the wake up feature works but my assumption is that it would take big chunks of audio and send them to the STT service to see if a hotword was included. I don't think I would recommend whisper-rhasspy-http for hotword detection.

To diagnose this further are you able to extract one of wav sent while doing STT ? Are you also able to get the logs for whisper-rhasppy-http ?

**Comment by luzik** [comment]
nevermind .. I switched to  rhasspy/wyoming-whisper. It can be closed
